# Generated by Django 5.1.3 on 2025-08-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='subject_photos/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('promotion_end_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'ຊາຍ'), ('F', 'ຍິງ'), ('o ', 'ພຣະ')], max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('name_eng', models.CharField(max_length=60)),
                ('age', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('tel', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=60)),
                ('districts', models.CharField(max_length=60)),
                ('village', models.CharField(max_length=60)),
                ('from_school', models.CharField(max_length=60)),
                ('academic_year', models.CharField(max_length=60)),
                ('semester', models.CharField(max_length=60)),
                ('employee', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved')], default='unapproved', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('subject_set', models.ManyToManyField(to='myapp.subject')),
            ],
        ),
    ]
