# Generated by Django 5.2.5 on 2025-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='StudentID',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
