# Generated by Django 5.2.5 on 2025-08-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subscription_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gender',
            field=models.CharField(choices=[('ທ້າວ', 'ຊາຍ'), ('ນາງ', 'ຍິງ')], max_length=10),
        ),
    ]
