# Generated by Django 5.2.5 on 2025-08-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subscription_photo_alter_subscription_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image_field', models.ImageField(upload_to='')),
            ],
        ),
    ]
