# Generated by Django 5.2.5 on 2025-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Profile',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
