# Generated by Django 5.2.5 on 2025-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_subscription_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Current_districts',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Current_province',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Current_village',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
