# Generated by Django 5.2.5 on 2025-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_subscription_current_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Skill',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
