# Generated by Django 5.2.5 on 2025-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subscription_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
