# Generated by Django 5.2.5 on 2025-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_subscription_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subject',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
