# Generated by Django 5.2.5 on 2025-08-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_subscription_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='districts_school',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='province_school',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='village_school',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
