# Generated by Django 5.2.5 on 2025-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_subscription_districts_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='M',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
