# Generated by Django 5.2.5 on 2025-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_subscription_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Language',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
