# Generated by Django 5.2.5 on 2025-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_subscription_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Language1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Language2',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
