# Generated by Django 5.2.5 on 2025-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_subscription_language1_subscription_language2'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gender',
            field=models.CharField(choices=[('Mr', 'ຊາຍ'), ('Miss', 'ຍິງ')], max_length=10),
        ),
    ]
