# Generated by Django 5.2.5 on 2025-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subscription_nationality_alter_subscription_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Religion',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
