# Generated by Django 5.2.5 on 2025-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_subscription_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Other_Skill',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
