# Generated by Django 5.2.5 on 2025-08-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_subscription_other_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='M',
            new_name='Mo',
        ),
    ]
