# Generated by Django 5.2.5 on 2025-08-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_m_subscription_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subject_set',
        ),
    ]
