# Generated by Django 5.2.5 on 2025-08-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_subscription_subject_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Language_Level',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Language_Level1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Skill_full',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
