# Generated by Django 5.2.5 on 2025-08-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_subscription_language_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Language_Level',
            new_name='Level_Chi',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Language_Level1',
            new_name='Level_Eng',
        ),
    ]
