# Generated by Django 5.2.5 on 2025-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_language_level_subscription_level_chi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Ability1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Ability2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Ability3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='School',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Work',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=60),
        ),
    ]
