# Generated by Django 5.2.5 on 2025-08-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_subscription_ability1_subscription_ability2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Parents_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
