# Generated by Django 5.2.5 on 2025-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_subscription_parents_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Level_Chi',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Level_Eng',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Other_Skill',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
