# Generated by Django 5.2.5 on 2025-08-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_subscription_level_chi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Level_Chi',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Level_Eng',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Other_Skill',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
