# Generated by Django 5.2.5 on 2025-08-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_subscription_level_chi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Detail_Skill',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
