# Generated by Django 5.2.5 on 2025-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_subscription_detail_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Other_Skill',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Skill_full',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
