# Generated by Django 5.2.5 on 2025-08-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_subscription_other_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Detail_Skill',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Skill_full',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
