# Generated by Django 5.2.5 on 2025-08-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_subscription_detail_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Level_Chi',
            new_name='Language_Level1',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Level_Eng',
            new_name='Language_Level2',
        ),
    ]
